Controllers/OpenApiController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using PayementMVC.Interfaces;
using PayementMVC.Models;
using PayementMVC.Utility;
using System.Net.Http.Headers;
using System.Net.Mime;
using System.Text;
using System.Xml;
using System.Xml.Linq;

namespace PayementMVC.Controllers
{
    public class OpenApiController : Controller
    {
        private readonly IOpenApi _openapi;
        private readonly IGlobalVariable _global;
        private readonly HttpClient _httpClient;
        private readonly IWebHostEnvironment _env;


        public OpenApiController(IOpenApi openapi,IGlobalVariable globalVariable, HttpClient httpClient,IWebHostEnvironment webHost)
        {
            _openapi = openapi;
            _global = globalVariable;
            _httpClient = httpClient;
            _env= webHost;
        }

        public IActionResult Index()
        {
            var data = _openapi.GetAll();
            return View(data);
        }
        [HttpPost]
        public IActionResult Create(OpenApiModel model)
        {
            _openapi.Create(model);


            return RedirectToAction("Index");
        }
        public IActionResult Configure(int id)
        {
            var data = _openapi.GetById(id);
            return View(data);
        }


        public async Task<IActionResult> GetUrlJson(string url)
        {
            HttpClient client = new HttpClient();
            var response = await client.GetAsync(url);
            var abc = await response.Content.ReadAsStringAsync();
            var a = GenerateViewFromJson(abc);


            return Json(abc);
        }


        public void CheckNested(JObject root, JObject obj, ref Dictionary<string, JObject> myDict)
        {

            if (obj["$ref"] != null)
            {
                var a = obj["$ref"].ToString();
                var splitted = a.Replace("#/", "").Split("/");
                var path = string.Join(".", splitted);
                var modelname2 = path.Substring(path.LastIndexOf(".") + 1);
                JObject jToken = root.SelectToken(path) as JObject;
                myDict.Add(modelname2, jToken);
                CheckNested(root, jToken, ref myDict);
            }

        }

        public List<SchemaModel> GenerateViewFromJson(string json)
        {
            List<SchemaModel> myschemaList = new List<SchemaModel>();
            var root = JsonConvert.DeserializeObject<JObject>(json);
            var schemas = root.SelectToken("components.schemas") as JObject;
            foreach (var model in schemas.Properties())
            {
                SchemaModel myschema = new SchemaModel();
                myschema.ModelName = model.Name;

                var modelProperties = (JObject)model.Value;
                foreach (var property in modelProperties.Properties())
                {
                    if (property.Name == "additionalProperties")
                    {
                        continue;
                    }

                    if (property.Name == "properties")
                    {

                        var nestedObj = (JObject)property.Value;
                        foreach (var property2 in nestedObj.Properties())
                        {
                            var testignval = JObject.Parse(property2.Value.ToString());
                            var mydict = new Dictionary<string, JObject>();
                            CheckNested(root, testignval, ref mydict);
                            if (mydict.Count > 0)
                            {
                                myschema.haha.Add(property2.Name, mydict);
                            }
                            else
                            {
                                myschema.NestedPropertiesList.Add(property2.Name, testignval);

                            }


                        }
                    }
                    else
                    {
                        switch (property.Type)
                        {
                            case JTokenType.Object:
                            case JTokenType.Array:
                                break;

                            case JTokenType.Property:
                                myschema.PropertiesList.Add(property.Name, property.Value.ToString());
                                break;
                        }
                    }






                }
                myschemaList.Add(myschema);
            }
            return myschemaList;

        }



        public async Task<IActionResult> PartialViewForSchema(string url)
        {
            HttpClient client = new HttpClient();
            var response = await client.GetAsync(url);
            var abc = await response.Content.ReadAsStringAsync();
            var a = GenerateViewFromJson(abc);
            return PartialView("_SchemaView", a);

        }

        public List<JObject> GetListOfNestedJObject(JObject obj)
        {
            var JObjects = new List<JObject>();

            foreach (var property in obj.Properties())
            {
                if (property.Value.Type == JTokenType.Object)
                {
                    var nestedJObjects = GetListOfNestedJObject((JObject)property.Value);

                    foreach (var nestedJObject in nestedJObjects)
                    {
                        JObjects.Add(nestedJObject);
                    }


                }

            }

            return JObjects;
        }
        public class SchemaModel
        {
            public string ModelName { get; set; }
            public Dictionary<string, string> PropertiesList { get; set; } = new Dictionary<string, string>();
            public Dictionary<string, JObject> NestedPropertiesList { get; set; } = new Dictionary<string, JObject>();

            public Dictionary<string, Dictionary<string, JObject>> haha = new Dictionary<string, Dictionary<string, JObject>>();
        }




        public async Task<JsonResult> ExecuteApi(string url,string method, string mediaType,string? data,string? scheme,string? token)
        {
            HttpMethod httpMethod =new  HttpMethod(method);

            mediaType = String.IsNullOrEmpty(mediaType) ? "application/json" : mediaType;
            var request = new HttpRequestMessage(httpMethod, url);
            if (!string.IsNullOrWhiteSpace(scheme))
            {
                request.Headers.Authorization = new AuthenticationHeaderValue(scheme, token);
            }
            
      
            if (!string.IsNullOrEmpty(data)) 
            {
                var content = new StringContent(data, Encoding.UTF8, mediaType);
                content.Headers.ContentType = new MediaTypeHeaderValue(mediaType);
                request.Content = content;
            }
            
            
            try
            {
                var responseMessage = await _httpClient.SendAsync(request);

                var contentType = responseMessage.Content.Headers.ContentType !=null? responseMessage.Content.Headers.ContentType.MediaType : "";

                var values = await responseMessage.Content.ReadAsStringAsync();


                return Json(new { ResponseValue = values, ServerResponse = responseMessage ,ContentType= contentType });

            }
            catch (Exception ez)
            {
                return Json(ez);
            }
            
           
        }

        public IActionResult testingConfigure(int id)
        {
            var data = _openapi.GetById(id);
            return View(data);
        }

        public IActionResult Editor()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Editor(string code,string codeJson)
        {
            var webRootPath = _env.WebRootPath;

            var filePath = Path.Combine(webRootPath, "swagger", "openapi.json");
            var filePathYaml = Path.Combine(webRootPath, "swagger", "openapi.yaml");

            var directoryPath = Path.GetDirectoryName(filePath);
            if (!Directory.Exists(directoryPath))
            {
                Directory.CreateDirectory(directoryPath);
            }

            System.IO.File.WriteAllText(filePath, JsonConvert.DeserializeObject<object>( codeJson).ToString());
            System.IO.File.WriteAllText(filePathYaml, code);
          
            //PaymentApp
            System.IO.File.WriteAllText("C:\\Users\\OnePoint-bijay\\Desktop\\Projects\\OfficeProject\\PaymentApp\\wwwroot\\openapi.json", JsonConvert.DeserializeObject<object>(codeJson).ToString());
            System.IO.File.WriteAllText("C:\\Users\\OnePoint-bijay\\Desktop\\Projects\\OfficeProject\\PaymentApp\\wwwroot\\openapi.yaml", code);

            return RedirectToAction("Editor");
        }




        public IActionResult ParameterPartial() => PartialView("_Parameter");
        public IActionResult PathPartial() => PartialView("_Path");
        public IActionResult ResponsePartial() => PartialView("_Response");
    }


}

Views/OpenApi/Index.cshtml
@model IEnumerable<OpenApiModel>
@{
    ViewData["Title"] = "GetAllTransaction";


}

<h1>Open Api Hub </h1>

<p>
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Create </button>

</p>
<table class="table table-hover ">
    <thead>
        <tr>
            <td>Id</td>
            <td>Name</td>
            <td>Version</td>
            <td>Title</td>
            <td>Description</td>
            <td>Visibility</td>
            <td>Action</td>
        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model)
        {<tr>

            <td>@item.Id</td>
            <td>@item.Name</td>
            <td>@item.Version</td>
            <td>@item.Title</td>
            <td>@item.Description</td>
            <td>@item.Visibility.ToString()</td>
            <td><a asp-action="Configure" asp-route-id="@item.Id"  class="btn btn-warning"><i class="fa fa-wrench"></i>Config</a></td>
        </tr>
        }
    </tbody>
</table>


<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Create New</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form asp-action="Create" asp-controller="OpenApi" method="post">
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="recipient-name" class="col-form-label">Name:</label>
                                <input type="text" class="form-control" name="Name" />
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="message-text" class="col-form-label">Title:</label>
                                <input type="text" class="form-control" name="Title" />
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="message-text" class="col-form-label">Version:</label>
                                <input type="text" class="form-control" name="Version" />
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label for="message-text" class="col-form-label">Visibility:</label>
                                <select class="form-control" name="Visibility" asp-items="@Html.GetEnumSelectList<VisibilityEnum>()">
                                    <option value="">-- Select --</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="message-text" class="col-form-label">Description:</label>
                                <textarea rows="8" type="text" class="form-control" name="Description"></textarea>
                            </div>
                        </div>


                    </div>
                    <div class="row">
                        <button type="submit" class="btn btn-primary">Create New</button>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>
                </form>


            </div>

        </div>
    </div>
</div>

Views/OpenApi/_Api.cshtml
<div class="card" style="border:silver solid 1px; ">
    <div class="card-header d-flex p-0" style="border:silver solid 1px; ">
        <button type="button" class="btn">

            <span class="btn btn-success ">GET</span>
            <span class="path text-white "  >
                /WeatherForecast
            </span>


        </button>
    </div>
   

</div>

Views/OpenApi/_Parameter.cshtml
<div class="card card-body" style="border:1px dashed silver">

    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <label class="control-label">Name</label>
                <input type="text" class="form-control" />

            </div>

        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label class="control-label">Description</label>
                <textarea type="text" class="form-control"></textarea>

            </div>

        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label class="control-label">IN</label>
                <select class="form-control">
                    <option value="">query</option>
                    <option value="">path</option>
                    <option value="">header</option>
                    <option value="">cookie</option>
                </select>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label class="control-label">Schema</label>

                <input type="text" class="form-control" />

            </div>

        </div>
    </div>
</div>

Views/OpenApi/_Path.cshtml
<div class="card card-body" style="border:1px solid silver">
    <div class="row" style="margin-left:20px;">
        <div class="col-md-2">
            <div class="form-group">
                <label class="control-label">Method</label>
                <select class="form-control">
                    <option value="">GET</option>
                    <option value="">POST</option>
                    <option value="">PUT</option>
                    <option value="">DELETE</option>
                </select>

            </div>

        </div>

        <div class="col-md-4">
            <div class="form-group">
                <label class="control-label">Name</label>
                <input type="text" class="form-control" />

            </div>

        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label class="">Description</label>
                <textarea cols="9" type="text" class="form-control"></textarea>
            </div>
        </div>
        <div style="display:block">

            <div class="parameters">
                <button type="button" class="btn btn-success btn-sm" onclick="addParameter()">+ Add Parameters</button>
                <div id="noice">
                </div>
            </div>
            <br />
            <div class="response">
                <button type="button" class="btn btn-success btn-sm" onclick="addResponse()">+ Add Response</button>
                <div id="responseList">
                </div>
            </div>
        </div>

    </div>

</div>

Views/OpenApi/_Response.cshtml
<div class="card card-body" style="border:1px dashed silver">

    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <label class="control-label">Status Code</label>
                <input type="text" class="form-control" />

            </div>

        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label class="control-label">Description</label>
                <textarea type="text" class="form-control"></textarea>

            </div>

        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label class="control-label">Content</label>
                <select class="form-control">
                    <option value="">application/json</option>
                    <option value="">application/xml</option>
                </select>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label class="control-label">Schema</label>

                <input type="text" class="form-control" />

            </div>

        </div>
    </div>
</div>

Views/OpenApi/_SchemaView.cshtml
@using Newtonsoft.Json.Linq
@using static PayementMVC.Controllers.OpenApiController
@model IEnumerable<SchemaModel>


@foreach (var item in Model)
{
    <div class="card" style="border:dotted silver 1px">
        <div class="card-header">
            <button type="button" class="btn text-white " onclick="openCardCollapse(this)">@item.ModelName</button>



        </div>
        <div class="card-body" width="100%">
            <div class="collapse">
                <table class="table ">
                    <tbody>
                        @foreach (var property in item.PropertiesList)
                        {
                            <tr>
                                <td>@property.Key</td>
                                <td>@property.Value</td>
                            </tr>
                        }
                        @foreach (var property in item.NestedPropertiesList)
                        {
                            <tr>
                                <td>
                                    @property.Key:

                                </td>
                                <td>
                                    @foreach (var nestedprop in property.Value.Properties())
                                    {
                                        if (nestedprop.Name == "properties")
                                        {
                                            var nestedpropobj = JObject.Parse(nestedprop.Value.ToString());
                                            foreach (var nestedobjprops in nestedpropobj.Properties())
                                            {
                                                <p> @nestedobjprops.Name: @nestedobjprops.Value</p>
                                            }
                                        }
                                        else
                                        {
                                            <p> @nestedprop.Name: @nestedprop.Value</p>

                                        }

                                    }

                                </td>

                            </tr>
                        }
                        @if (item.haha.Values.Count() > 0)
                        {
                            @foreach (var nestedobj in item.haha)
                            {
                                <tr>
                                    <td>@nestedobj.Key </td>
                                    @foreach (var nestedval in nestedobj.Value)
                                    {
                                        <td>@nestedval.Key <p> @nestedval.Value</p> </td>
                                       
                                    }
                                   
                                </tr>
                            }
                        }

                    </tbody>

                </table>

            </div>
        </div>
    </div>
}

Views/OpenApi/_configurepart.cshtml
@model OpenApiModel

<div class="box d-flex" style="gap:10px;">
    <div class="card" style="width:20%;">
        <div class="card-body">
            <div class="card">
                <div class="card-header ">
                    <div style="display:flex; justify-content:space-between">
                        <h6>Schemas</h6>
                        <button type="button" class="btn btn-success btn-xs"> + Add</button>
                    </div>

                </div>
            </div>
            <div class="card">
                <div class="card-header">
                    <div style="display:flex; justify-content:space-between">
                        <h6>Tags <i class="fa fa-arrow-down fa-xs"></i> </h6>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <div class="card" style="width:50%">
        <div class="card-body">

            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label class="control-label">Name</label>
                        <input type="text" class="form-control" asp-for="Name" />

                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label class="control-label">Version</label>
                        <input type="text" class="form-control" asp-for="Version" />

                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label class="control-label">Title</label>
                        <input type="text" class="form-control" asp-for="Title" />

                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label class="control-label">Description</label>
                        <textarea type="text" class="form-control" asp-for="Description"></textarea>

                    </div>
                </div>
            </div>
            <div class="card">

                <div class="card card-header ">
                    <div>
                        <h4>Paths</h4>
                        <button type="button" class="btn btn-success btn-xs" onclick="addPath()">+ Add</button>
                    </div>
                </div>
                <div id="pathlist">
                </div>

            </div>

        </div>
    </div>


    <!--Test-->
    <div class="card d-flex" style="width:40%">
        <div class="card-body">
            <h5>@Model.Name</h5>
            <div class="details">
                <button class="btn btn-secondary btn-xs">1.0</button>
                <button class="btn btn-success btn-xs">OAS 3.0.0</button>
                <p>
                    @Model.Description
                </p>
            </div>

            <div class="apis">
                <div class="card">
                    <div class="card-header">
                        <div style="display:flex; justify-content:space-between">
                            <h6>Tags  </h6>
                            <button type="button" class="btn btn-secondary" aria-controls="apibody" data-toggle="collapse" data-target="#apibody"><i class="fa fa-arrow-down"></i> </button>
                        </div>
                    </div>

                    <div class="collapse" id="apibody">
                        <div class="card-body">
                            <div class="card">
                                <div class="card-header" style="border:lightgreen solid 1px">
                                    <button type="button" class="btn btn-success">GET</button>

                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>

            <div class="schemas">
                <div class="card">
                    <div class="card-header">
                        <div style="display:flex; justify-content:space-between">
                            <h6>Schemas  </h6>
                            <button type="button" class="btn btn-secondary" aria-controls="apibody" data-toggle="collapse" data-target="#schemasBody"><i class="fa fa-arrow-down"></i> </button>
                        </div>
                    </div>

                    <div class="collapse" id="schemasBody">
                        <div class="card-body">
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>


<script type="text/javascript">
    function addPath() {
        $.ajax({
            url: "@Url.Action("PathPartial")",
            success: function (data) {
                $("#pathlist").append(data);
            }
        })
    }


    function addParameter() {
        $.ajax({
            url: "@Url.Action("ParameterPartial")",
            success: function (data) {
                $("#noice").append(data);
            }
        })
    }
    function addResponse() {
        $.ajax({
            url: "@Url.Action("ResponsePartial")",
            success: function (data) {
                $("#responseList").append(data);
            }
        })
    }

</script>